import {
  CalendarDays,
  FileText,
  FolderOpen,
  Handshake,
  LayoutDashboard,
  Settings,
  ShieldCheck,
  Users,
  UserCircle2,
  History,
  Bell,
} from 'lucide-react'

import type {
  BaseDataItem,
  EngagementRecord,
  EventRecord,
  NavigationItem,
  OpportunityRecord,
  PartnerRecord,
  AgreementRecord,
  RoleRecord,
  UserRecord,
  AuditLogRecord,
  NotificationRecord,
} from './types'

export const navigationItems: NavigationItem[] = [
  { label: 'Dashboard', page: 'dashboard', icon: LayoutDashboard, group: 'DASHBOARD' },
  { label: 'Events & Visits', page: 'events', icon: CalendarDays, group: 'MAIN' },
  { label: 'Opportunities', page: 'opportunities', icon: Handshake, group: 'MAIN' },
  { label: 'Engagement', page: 'engagement', icon: FolderOpen, group: 'MAIN' },
  { label: 'Agreements', page: 'agreements', icon: FileText, group: 'MAIN' },
  { label: 'Partners', page: 'partners', icon: Users, group: 'MAIN' },
  { label: 'Base Data', page: 'baseData', icon: FileText, group: 'BASE DATA' },
  { label: 'Users', page: 'users', icon: UserCircle2, group: 'USER MANAGEMENT' },
  { label: 'Roles', page: 'roles', icon: ShieldCheck, group: 'USER MANAGEMENT' },
  {
    label: 'Permission Actions',
    page: 'permission-actions',
    icon: Settings,
    group: 'USER MANAGEMENT',
  },
  {
    label: 'Permission Resources',
    page: 'permission-resources',
    icon: Layers,
    group: 'USER MANAGEMENT',
  },
  {
    label: 'Audit Logs',
    page: 'audit-logs',
    icon: History,
    group: 'SYSTEM SETTINGS',
  },
  {
    label: 'Notifications',
    page: 'notifications',
    icon: Bell,
    group: 'SYSTEM SETTINGS',
  },
]

export const events: EventRecord[] = [
  // ── DRAFT (Officer can edit & submit) ────────────────────────────────────
  {
    id: 'evt-001',
    no: 1,
    title: 'AI Innovation Summit 2025',
    type: 'Conference',
    date: '2025-09-15T08:30',
    venue: 'Skylight Hotel, Addis Ababa',
    status: 'Draft',
    category: 'Event',
    eventCategory: 'Joint',
    startTime: '08:30',
    endTime: '17:30',
    partnerParticipants: [
      {
        id: 'pp-1',
        fullName: 'Dr. John Doe',
        organizationName: 'UN Global AI',
        position: 'Director of AI Policy',
        email: 'john.doe@unga.org',
        phone: '+15550199',
        type: 'Speaker',
      },
    ],
    eaiiParticipants: [
      { name: 'Abebe Kebede', division: 'AI Research', email: 'abebe.k@eaii.gov.et' },
    ],
    estimatedBudget: 50000,
    attachmentsAgenda: 'agenda_summit_2025.pdf',
  },
  {
    id: 'evt-002',
    no: 2,
    title: 'EAII Robotics Hackathon',
    type: 'Hackathon',
    date: '2025-10-10T09:00',
    venue: 'EAII Main Hall',
    status: 'Draft',
    category: 'Event',
    eventCategory: 'Internal',
    startTime: '09:00',
    endTime: '18:00',
    organizer: 'Ethiopian AI Institute',
    eventMode: 'Physically',
    estimatedBudget: 15000,
  },

  // ── PENDING REVIEW (DG needs to act) ──────────────────────────────────────
  {
    id: 'evt-003',
    no: 3,
    title: 'National AI Symposium',
    type: 'Conference',
    date: '2025-11-10T09:00',
    venue: 'Sheraton Addis, Addis Ababa',
    status: 'Pending Review',
    category: 'Event',
    eventCategory: 'Joint',
    startTime: '09:00',
    endTime: '17:00',
    organizer: 'Ethiopian AI Institute',
    coOrganizer: 'African Development Bank',
    eventMode: 'Physically',
    estimatedBudget: 80000,
    partnerParticipants: [
      {
        id: 'pp-3a',
        fullName: 'Mr. Kwame Mensah',
        organizationName: 'African Development Bank',
        position: 'Head of Digital Innovation',
        email: 'k.mensah@afdb.org',
        phone: '+22612345678',
        type: 'VIP Guest',
      },
    ],
    eaiiParticipants: [
      { name: 'Tigist Alemu', division: 'Strategic Partnerships', email: 'tigist.a@eaii.gov.et' },
    ],
    auditTrail: [
      {
        actorName: 'Dawit Haile',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-09-28T09:15:00Z',
      },
    ],
  },
  {
    id: 'evt-004',
    no: 4,
    title: 'Incoming Visit from UNESCO Digital Division',
    type: 'Incoming visit',
    date: '2025-11-05T10:00',
    venue: 'EAII Headquarters',
    status: 'Pending Review',
    category: 'Visit',
    visitType: 'Incoming visit',
    visitCategory: 'international',
    visitDate: '2025-11-05',
    hostOrganization: 'Ethiopian AI Institute',
    visitingOrganization: 'UNESCO',
    visitLocations: 'EAII Headquarters, AI Research Wing',
    purposeOfVisit: 'Explore feasibility of a joint digital literacy initiative for East Africa.',
    focalPersonName: 'Belay Tadesse',
    focalPersonDivision: 'International Relations',
    focalPersonEmail: 'belay.t@eaii.gov.et',
    delegations: [
      {
        fullName: 'Ms. Isabelle Dupont',
        position: 'Programme Specialist',
        organizationName: 'UNESCO',
        country: 'France',
        email: 'i.dupont@unesco.org',
        phone: '+33123456789',
        status: 'VIP',
      },
    ],
    auditTrail: [
      {
        actorName: 'Selam Worku',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-10-30T11:00:00Z',
      },
    ],
  },

  // ── APPROVED (Assigned Person needs to fill outcomes) ─────────────────────
  {
    id: 'evt-005',
    no: 5,
    title: 'Google DeepMind Technical Visit',
    type: 'technical visit',
    date: '2025-05-20T10:00',
    venue: 'EAII Headquarters, Addis Ababa',
    status: 'Approved',
    category: 'Visit',
    visitType: 'technical visit',
    visitCategory: 'international',
    visitDate: '2025-05-20',
    hostOrganization: 'Ethiopian AI Institute',
    visitingOrganization: 'Google DeepMind',
    visitLocations: 'Computer Vision Lab, NLP Division',
    purposeOfVisit: 'Collaborative research exploration on low-resource language translation.',
    focalPersonName: 'Dr. Yonas M.',
    focalPersonDivision: 'Natural Language Processing',
    focalPersonEmail: 'yonas.m@eaii.gov.et',
    assignedPerson: 'Hiwot Girma',
    assignedPersonId: 'usr-hiwot',
    outcomeDueDate: '2025-06-20',
    reviewComment: 'Please document all technical discussion outcomes and follow-up commitments.',
    delegations: [
      {
        fullName: 'Dr. Sarah Jenkins',
        position: 'Research Scientist',
        organizationName: 'Google DeepMind',
        country: 'United Kingdom',
        email: 'sjenkins@google.com',
        phone: '+447911123456',
        status: 'VIP',
      },
    ],
    auditTrail: [
      {
        actorName: 'Dawit Haile',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-06-01T08:30:00Z',
      },
      {
        actorName: 'Dir. General Abebe',
        actorRole: 'Director General',
        actionLabel: 'Approved',
        previousStatus: 'Pending Review',
        newStatus: 'Approved',
        timestamp: '2025-06-05T14:00:00Z',
        comment: 'Please document all technical discussion outcomes and follow-up commitments.',
      },
    ],
  },
  {
    id: 'evt-006',
    no: 6,
    title: 'Exhibition on AI in Healthcare',
    type: 'Exhibition',
    date: '2025-04-02T09:00',
    venue: 'Skylight Hotel',
    status: 'Approved',
    category: 'Event',
    eventCategory: 'Joint',
    startTime: '09:00',
    endTime: '17:00',
    organizer: 'Ethiopian AI Institute',
    coOrganizer: 'Ministry of Health',
    eventMode: 'Physically',
    estimatedBudget: 35000,
    assignedPerson: 'Tigist Alemu',
    assignedPersonId: 'usr-tigist',
    outcomeDueDate: '2025-05-15',
    reviewComment: 'Capture all partnership leads from the healthcare sector.',
    auditTrail: [
      {
        actorName: 'Selam Worku',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-03-20T10:00:00Z',
      },
      {
        actorName: 'Dir. General Abebe',
        actorRole: 'Director General',
        actionLabel: 'Approved',
        previousStatus: 'Pending Review',
        newStatus: 'Approved',
        timestamp: '2025-03-25T09:00:00Z',
        comment: 'Capture all partnership leads from the healthcare sector.',
      },
    ],
  },

  // ── PENDING FINAL REVIEW (DG must complete) ────────────────────────────────
  {
    id: 'evt-007',
    no: 7,
    title: 'Delegation Visit from AU Commission',
    type: 'delegation visit',
    date: '2025-03-18T14:00',
    venue: 'EAII Headquarters',
    status: 'Pending Final Review',
    category: 'Visit',
    visitType: 'delegation visit',
    visitCategory: 'international',
    visitDate: '2025-03-18',
    hostOrganization: 'Ethiopian AI Institute',
    visitingOrganization: 'African Union Commission',
    visitLocations: 'Exhibition Center',
    purposeOfVisit: 'Familiarization with African AI strategy initiative.',
    focalPersonName: 'Aster Tolossa',
    focalPersonDivision: 'Public Relations',
    focalPersonEmail: 'aster.t@eaii.gov.et',
    assignedPerson: 'Belay Tadesse',
    assignedPersonId: 'usr-belay',
    outcomeDueDate: '2025-04-10',
    delegations: [
      {
        fullName: 'Ambassador Bankole Adeoye',
        position: 'Commissioner',
        organizationName: 'AU Commission',
        country: 'Nigeria',
        email: 'adeoyeb@africa-union.org',
        phone: '+251115517700',
        status: 'VIP',
      },
    ],
    keyTopicsDiscussed: 'Continental AI policy alignment, shared data governance frameworks.',
    opportunitiesIdentified: 'AU-EAII joint AI research fund, capacity building program.',
    visitAgreementsReached: 'Establish a formal MoU within 6 months.',
    followUpActions:
      'Prepare draft MoU template and share with AU Commission legal team by April 30.',
    auditTrail: [
      {
        actorName: 'Dawit Haile',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-03-01T08:00:00Z',
      },
      {
        actorName: 'Dir. General Abebe',
        actorRole: 'Director General',
        actionLabel: 'Approved',
        previousStatus: 'Pending Review',
        newStatus: 'Approved',
        timestamp: '2025-03-05T11:00:00Z',
      },
      {
        actorName: 'Belay Tadesse',
        actorRole: 'Assigned Person',
        actionLabel: 'Outcome Submitted',
        previousStatus: 'Approved',
        newStatus: 'Pending Final Review',
        timestamp: '2025-03-25T16:30:00Z',
      },
    ],
  },

  // ── COMPLETED ──────────────────────────────────────────────────────────────
  {
    id: 'evt-008',
    no: 8,
    title: 'Joint AI Research Workshop — AAU',
    type: 'Workshop',
    date: '2025-02-05T09:00',
    venue: 'EAII Seminar Room',
    status: 'Completed',
    category: 'Event',
    eventCategory: 'Joint',
    startTime: '09:00',
    endTime: '16:00',
    organizer: 'Ethiopian AI Institute',
    coOrganizer: 'Addis Ababa University',
    eventMode: 'Physically',
    estimatedBudget: 20000,
    actualBudget: 19200,
    fundingScore: 8.0,
    assignedPerson: 'Hiwot Girma',
    assignedPersonId: 'usr-hiwot',
    keyDiscussions: 'NLP research collaboration, shared datasets for Amharic language models.',
    agreementsReached: 'Joint publication agreement on Amharic NLP benchmarks.',
    actionPoints: 'Submit joint paper to ACL 2025 by end of March.',
    objectivesAchieved: 'Established a working group with AAU Computer Science dept.',
    recommendations: 'Formalize MoU for long-term lab access and data sharing.',
    auditTrail: [
      {
        actorName: 'Selam Worku',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-01-15T09:00:00Z',
      },
      {
        actorName: 'Dir. General Abebe',
        actorRole: 'Director General',
        actionLabel: 'Approved',
        previousStatus: 'Pending Review',
        newStatus: 'Approved',
        timestamp: '2025-01-20T11:00:00Z',
      },
      {
        actorName: 'Hiwot Girma',
        actorRole: 'Assigned Person',
        actionLabel: 'Outcome Submitted',
        previousStatus: 'Approved',
        newStatus: 'Pending Final Review',
        timestamp: '2025-02-10T15:00:00Z',
      },
      {
        actorName: 'Dir. General Abebe',
        actorRole: 'Director General',
        actionLabel: 'Completed',
        previousStatus: 'Pending Final Review',
        newStatus: 'Completed',
        timestamp: '2025-02-15T10:00:00Z',
      },
    ],
  },

  // ── REJECTED ───────────────────────────────────────────────────────────────
  {
    id: 'evt-009',
    no: 9,
    title: 'AI Policy Webinar',
    type: 'Webinar',
    date: '2025-08-01T15:00',
    venue: 'Zoom Video Conferencing',
    status: 'Rejected',
    category: 'Event',
    eventCategory: 'Internal',
    startTime: '15:00',
    endTime: '16:30',
    organizer: 'Ethiopian AI Institute',
    eventMode: 'Virtual',
    rejectionReason:
      'Scope too narrow; please expand to include regional policy stakeholders and resubmit.',
    auditTrail: [
      {
        actorName: 'Dawit Haile',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-07-10T09:00:00Z',
      },
      {
        actorName: 'Dir. General Abebe',
        actorRole: 'Director General',
        actionLabel: 'Rejected',
        previousStatus: 'Pending Review',
        newStatus: 'Rejected',
        timestamp: '2025-07-12T14:00:00Z',
        comment: 'Scope too narrow; please expand to include regional policy stakeholders.',
      },
    ],
  },
  {
    id: 'evt-010',
    no: 10,
    title: 'Benchmarking Visit to Ethio Telecom',
    type: 'benchmarking visit',
    date: '2025-02-12T10:00',
    venue: 'Ethio Telecom Data Center',
    status: 'Rejected',
    category: 'Visit',
    visitType: 'benchmarking visit',
    visitCategory: 'external',
    visitDate: '2025-02-12',
    hostOrganization: 'Ethio Telecom',
    visitingOrganization: 'Ethiopian AI Institute',
    purposeOfVisit: 'Benchmarking high-density cooling systems and fiber layout.',
    rejectionReason:
      'Insufficient technical justification. Please add specific benchmarking criteria and expected outcomes.',
    auditTrail: [
      {
        actorName: 'Selam Worku',
        actorRole: 'Officer',
        actionLabel: 'Submitted',
        previousStatus: 'Draft',
        newStatus: 'Pending Review',
        timestamp: '2025-01-28T10:00:00Z',
      },
      {
        actorName: 'Dir. General Abebe',
        actorRole: 'Director General',
        actionLabel: 'Rejected',
        previousStatus: 'Pending Review',
        newStatus: 'Rejected',
        timestamp: '2025-01-31T16:00:00Z',
        comment: 'Insufficient technical justification provided.',
      },
    ],
  },
]

export const opportunities: OpportunityRecord[] = [
  {
    id: 'opp-001',
    no: 1,
    title: 'UNESCO Digital Transformation Partnership',
    source: 'UNESCO outreach',
    date: '14 APR 2020',
    division: 'Finance',
    status: 'Draft',
  },
  {
    id: 'opp-002',
    no: 2,
    title: 'Joint AI Research Lab with Google DeepMind',
    source: 'AI Innovation Summit',
    date: '24 FEB 2020',
    division: 'Marketing',
    status: 'Draft',
  },
  {
    id: 'opp-003',
    no: 3,
    title: 'Scholarship Program',
    source: 'AI Innovation Summit',
    date: '24 FEB 2020',
    division: 'Product',
    status: 'Approved',
  },
  {
    id: 'opp-004',
    no: 4,
    title: 'UNESCO Digital Transformation Partnership',
    source: 'UNESCO outreach',
    date: '12 FEB 2020',
    division: 'Engineering',
    status: 'Approved',
  },
  {
    id: 'opp-005',
    no: 5,
    title: 'UNESCO Digital Transformation Partnership',
    source: 'UNESCO outreach',
    date: '26 MAR 2020',
    division: 'Business',
    status: 'Approved',
  },
  {
    id: 'opp-006',
    no: 6,
    title: 'UNESCO Digital Transformation Partnership',
    source: 'AI Innovation Summit',
    date: '15 MAR 2020',
    division: 'Design',
    status: 'Approved',
  },
  {
    id: 'opp-007',
    no: 7,
    title: 'Scholarship Program',
    source: 'AI Innovation Summit',
    date: '10 MAR 2020',
    division: 'Market Management',
    status: 'Pending Approval',
  },
  {
    id: 'opp-008',
    no: 8,
    title: 'Scholarship Program',
    source: 'AI Innovation Summit',
    date: '3 FEB 2020',
    division: 'Core Platform',
    status: 'Rejected',
  },
  {
    id: 'opp-009',
    no: 9,
    title: 'Joint AI Research Lab with Google DeepMind',
    source: 'UNESCO outreach',
    date: '28 APR 2020',
    division: 'Production System',
    status: 'Rejected',
  },
  {
    id: 'opp-010',
    no: 10,
    title: 'Joint AI Research Lab with Google DeepMind',
    source: 'UNESCO outreach',
    date: '17 MAR 2020',
    division: 'Finance',
    status: 'Draft',
  },
]

export const engagements: EngagementRecord[] = [
  { id: 'eng-001', no: 1, type: 'Negotiation', date: '14 APR 2020', status: 'Draft' },
  { id: 'eng-002', no: 2, type: 'Workshop', date: '24 FEB 2020', status: 'Draft' },
  { id: 'eng-003', no: 3, type: 'Meeting', date: '24 FEB 2020', status: 'Approved' },
  { id: 'eng-004', no: 4, type: 'Follow-Up', date: '12 FEB 2020', status: 'Approved' },
  { id: 'eng-005', no: 5, type: 'Site Visit', date: '26 MAR 2020', status: 'Approved' },
  { id: 'eng-006', no: 6, type: 'Negotiation', date: '15 MAR 2020', status: 'Approved' },
  { id: 'eng-007', no: 7, type: 'Negotiation', date: '10 MAR 2020', status: 'Assigned' },
  { id: 'eng-008', no: 8, type: 'Workshop', date: '3 FEB 2020', status: 'Rejected' },
  { id: 'eng-009', no: 9, type: 'Workshop', date: '28 APR 2020', status: 'Rejected' },
  { id: 'eng-010', no: 10, type: 'Negotiation', date: '17 MAR 2020', status: 'Pending Approval' },
]

export const agreements: AgreementRecord[] = [
  {
    id: 'agr-001',
    no: 1,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '14 APR 2020',
    startDate: '14 APR 2020',
    endDate: '14 APR 2021',
    status: 'Draft',
  },
  {
    id: 'agr-002',
    no: 2,
    title: 'Research Collaboration Framework',
    type: 'MoU',
    date: '24 FEB 2020',
    startDate: '24 FEB 2020',
    endDate: '24 FEB 2021',
    status: 'Draft',
  },
  {
    id: 'agr-003',
    no: 3,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '24 FEB 2020',
    startDate: '24 FEB 2020',
    endDate: '24 FEB 2021',
    status: 'Approved',
  },
  {
    id: 'agr-004',
    no: 4,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '12 FEB 2020',
    startDate: '12 FEB 2020',
    endDate: '12 FEB 2021',
    status: 'Approved',
  },
  {
    id: 'agr-005',
    no: 5,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '26 MAR 2020',
    startDate: '26 MAR 2020',
    endDate: '26 MAR 2021',
    status: 'Accepted',
  },
  {
    id: 'agr-006',
    no: 6,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '15 MAR 2020',
    startDate: '15 MAR 2020',
    endDate: '15 MAR 2021',
    status: 'Accepted',
  },
  {
    id: 'agr-007',
    no: 7,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '10 MAR 2020',
    startDate: '10 MAR 2020',
    endDate: '10 MAR 2021',
    status: 'Accepted',
  },
  {
    id: 'agr-008',
    no: 8,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '3 FEB 2020',
    startDate: '3 FEB 2020',
    endDate: '3 FEB 2021',
    status: 'Rejected',
  },
  {
    id: 'agr-009',
    no: 9,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '28 APR 2020',
    startDate: '28 APR 2020',
    endDate: '28 APR 2021',
    status: 'Rejected',
  },
  {
    id: 'agr-010',
    no: 10,
    title: 'MoU for AI Capacity Building',
    type: 'MoU',
    date: '17 MAR 2020',
    startDate: '17 MAR 2020',
    endDate: '17 MAR 2021',
    status: 'Accepted',
  },
]

export const partners: PartnerRecord[] = [
  {
    id: 'prt-001',
    no: 1,
    name: 'Individual Booking Engine',
    type: 'International Organization',
    country: 'USA',
    organization: 'CBRE',
    contact: 'Akash Maurya',
    status: 'Draft',
  },
  {
    id: 'prt-002',
    no: 2,
    name: 'Web Individual',
    type: 'Private Sector',
    country: 'UK',
    organization: 'Google',
    contact: 'Sidharth Yadav',
    status: 'Draft',
  },
  {
    id: 'prt-003',
    no: 3,
    name: 'Hotel added to BE Corpo',
    type: 'Private Sector',
    country: 'Russia',
    organization: 'OWP',
    contact: 'Naushad Khan',
    status: 'Approved',
  },
  {
    id: 'prt-004',
    no: 4,
    name: 'Hotel added to Web Corpo',
    type: 'Private Sector',
    country: 'China',
    organization: 'OWP',
    contact: 'Santosh Machindra',
    status: 'Approved',
  },
  {
    id: 'prt-005',
    no: 5,
    name: 'Web Corpo',
    type: 'Academic',
    country: 'France',
    organization: 'CBRE',
    contact: 'Devendra Sharma',
    status: 'Accepted',
  },
  {
    id: 'prt-006',
    no: 6,
    name: 'Web Corpo',
    type: 'Academic',
    country: 'India',
    organization: 'Google',
    contact: 'Amit Singh',
    status: 'Accepted',
  },
  {
    id: 'prt-007',
    no: 7,
    name: 'Other',
    type: 'Academic',
    country: 'India',
    organization: 'CW',
    contact: 'Digvijay Katiyar',
    status: 'Accepted',
  },
  {
    id: 'prt-008',
    no: 8,
    name: 'Web Individual',
    type: 'Academic',
    country: 'China',
    organization: 'OWP',
    contact: 'Kapil Kumar Sengar',
    status: 'Rejected',
  },
  {
    id: 'prt-009',
    no: 9,
    name: 'Corpo Booking Engine',
    type: 'International Organization',
    country: 'Russia',
    organization: 'CW',
    contact: 'Vinayak Kamble',
    status: 'Rejected',
  },
  {
    id: 'prt-010',
    no: 10,
    name: 'Corpo Booking Engine',
    type: 'International Organization',
    country: 'France',
    organization: 'CW',
    contact: 'Kamal Verma',
    status: 'Accepted',
  },
]

export const baseData: BaseDataItem[] = [
  {
    id: 'base-001',
    title: 'Administration',
    description: 'This is the place to set administration address',
  },
  { id: 'base-002', title: 'Sector', description: 'This is the place to set Sector' },
  {
    id: 'base-003',
    title: 'Opportunity Source',
    description: 'This is the place to set opportunity source',
  },
]

export const users: UserRecord[] = [
  {
    id: 'usr-001',
    no: 1,
    name: 'Ralph Edwards',
    email: 'felicia.reid@example.com',
    phone: '+251 911 34 22 12',
    position: 'Content Writer',
    status: 'Active',
  },
  {
    id: 'usr-002',
    no: 2,
    name: 'Guy Hawkins',
    email: 'debra.holt@example.com',
    phone: '+251 911 34 22 12',
    position: 'Design Operation Lead',
    status: 'Active',
  },
  {
    id: 'usr-003',
    no: 3,
    name: 'Wade Warren',
    email: 'georgia.young@example.com',
    phone: '+251 911 34 22 12',
    position: 'Visual Designer',
    status: 'Active',
  },
  {
    id: 'usr-004',
    no: 4,
    name: 'Theresa Webb',
    email: 'alma.lawson@example.com',
    phone: '+251 911 34 22 12',
    position: 'Design Lead',
    status: 'Active',
  },
  {
    id: 'usr-005',
    no: 5,
    name: 'Floyd Miles',
    email: 'debbie.baker@example.com',
    phone: '+251 911 34 22 12',
    position: 'Data Analyst',
    status: 'Active',
  },
  {
    id: 'usr-006',
    no: 6,
    name: 'Robert Fox',
    email: 'jackson.graham@example.com',
    phone: '+251 911 34 22 12',
    position: 'Design Manager',
    status: 'Active',
  },
  {
    id: 'usr-007',
    no: 7,
    name: 'Brooklyn Simmons',
    email: 'michael.mitc@example.com',
    phone: '+251 911 34 22 12',
    position: 'Senior Product Manager',
    status: 'Active',
  },
  {
    id: 'usr-008',
    no: 8,
    name: 'Cody Fisher',
    email: 'kenzi.lawson@example.com',
    phone: '+251 911 34 22 12',
    position: 'Engineering Lead (Backend)',
    status: 'Active',
  },
  {
    id: 'usr-009',
    no: 9,
    name: 'Jacob Jones',
    email: 'nathan.roberts@example.com',
    phone: '+251 911 34 22 12',
    position: 'Product Admin',
    status: 'Active',
  },
  {
    id: 'usr-010',
    no: 10,
    name: 'Bessie Cooper',
    email: 'jessica.hanson@example.com',
    phone: '+251 911 34 22 12',
    position: 'Product Executive',
    status: 'Active',
  },
]

export const permissionActions = [
  { id: 1, action: 'Create' },
  { id: 2, action: 'Read' },
  { id: 3, action: 'Update' },
  { id: 4, action: 'Delete' },
  { id: 5, action: 'Authorize' },
  { id: 6, action: 'Verify' },
]

export const permissionResources = [
  { id: 1, name: 'Opportunities' },
  { id: 2, name: 'Engagements' },
  { id: 3, name: 'Agreements' },
  { id: 4, name: 'Partners' },
  { id: 5, name: 'Users' },
  { id: 6, name: 'Roles' },
]

export const roles: RoleRecord[] = [
  {
    id: 'role-001',
    no: 1,
    name: 'Administrator',
    description: 'Full platform access',
    rolePermissionResources: [
      {
        permission_resource_id: 1,
        rolePermissionResourceActions: [
          { permission_action_id: 1 },
          { permission_action_id: 2 },
          { permission_action_id: 3 },
          { permission_action_id: 4 },
          { permission_action_id: 5 },
          { permission_action_id: 6 },
        ],
      },
      {
        permission_resource_id: 2,
        rolePermissionResourceActions: [
          { permission_action_id: 1 },
          { permission_action_id: 2 },
          { permission_action_id: 3 },
          { permission_action_id: 4 },
          { permission_action_id: 5 },
          { permission_action_id: 6 },
        ],
      },
      {
        permission_resource_id: 3,
        rolePermissionResourceActions: [
          { permission_action_id: 1 },
          { permission_action_id: 2 },
          { permission_action_id: 3 },
          { permission_action_id: 4 },
          { permission_action_id: 5 },
          { permission_action_id: 6 },
        ],
      },
      {
        permission_resource_id: 4,
        rolePermissionResourceActions: [
          { permission_action_id: 1 },
          { permission_action_id: 2 },
          { permission_action_id: 3 },
          { permission_action_id: 4 },
          { permission_action_id: 5 },
          { permission_action_id: 6 },
        ],
      },
      {
        permission_resource_id: 5,
        rolePermissionResourceActions: [
          { permission_action_id: 1 },
          { permission_action_id: 2 },
          { permission_action_id: 3 },
          { permission_action_id: 4 },
          { permission_action_id: 5 },
          { permission_action_id: 6 },
        ],
      },
      {
        permission_resource_id: 6,
        rolePermissionResourceActions: [
          { permission_action_id: 1 },
          { permission_action_id: 2 },
          { permission_action_id: 3 },
          { permission_action_id: 4 },
          { permission_action_id: 5 },
          { permission_action_id: 6 },
        ],
      },
    ],
  },
  {
    id: 'role-002',
    no: 2,
    name: 'Finance Officer',
    description: 'Payment and reporting tools',
    rolePermissionResources: [
      {
        permission_resource_id: 3, // Agreements
        rolePermissionResourceActions: [{ permission_action_id: 2 }, { permission_action_id: 5 }],
      },
    ],
  },
  {
    id: 'role-003',
    no: 3,
    name: 'Support Agent',
    description: 'User support workflows',
    rolePermissionResources: [
      {
        permission_resource_id: 5, // Users
        rolePermissionResourceActions: [{ permission_action_id: 2 }],
      },
    ],
  },
  {
    id: 'role-004',
    no: 4,
    name: 'Auditor',
    description: 'Read-only review access',
    rolePermissionResources: [
      {
        permission_resource_id: 1,
        rolePermissionResourceActions: [{ permission_action_id: 2 }],
      },
      {
        permission_resource_id: 2,
        rolePermissionResourceActions: [{ permission_action_id: 2 }],
      },
      {
        permission_resource_id: 3,
        rolePermissionResourceActions: [{ permission_action_id: 2 }],
      },
      {
        permission_resource_id: 4,
        rolePermissionResourceActions: [{ permission_action_id: 2 }],
      },
    ],
  },
]

export const dashboardMetrics = [
  { label: 'Total Partners', value: '124' },
  { label: 'Open Opportunities', value: '58' },
  { label: 'Active Engagements', value: '18' },
]

export const dashboardActivity = [
  'New engagement workflow created',
  'Partnership agreement submitted for review',
  'AI research collaboration request approved',
  'Partner onboarding completed for new institution',
]

export const auditLogs: AuditLogRecord[] = [
  {
    id: 'al-1',
    action: 'Login',
    module: 'Auth',
    user: 'Alexander M.',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    details: 'User logged in successfully via SSO.',
  },
  {
    id: 'al-2',
    action: 'Create',
    module: 'Partner',
    user: 'Sarah K.',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    details: 'Created partner "Global Health Initiative".',
  },
  {
    id: 'al-3',
    action: 'Update',
    module: 'Agreement',
    user: 'Alexander M.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    details: 'Changed agreement status from Draft to Approved.',
  },
  {
    id: 'al-4',
    action: 'Delete',
    module: 'Opportunity',
    user: 'Admin User',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    details: 'Deleted draft opportunity #4021.',
  },
  {
    id: 'al-5',
    action: 'Export',
    module: 'Users',
    user: 'Sarah K.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    details: 'Exported 15 users to CSV.',
  },
  {
    id: 'al-6',
    action: 'Update',
    module: 'Role',
    user: 'Admin User',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    details: 'Updated permissions for "System Administrator" role.',
  },
]

export const notifications: NotificationRecord[] = [
  {
    id: 'notif-1',
    title: 'New Partnership Agreement',
    message: 'A new agreement with Ministry of Tech has been drafted and is awaiting review.',
    type: 'info',
    isRead: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    link: '/agreements',
  },
  {
    id: 'notif-2',
    title: 'Opportunity Approved',
    message: 'The AI Research Collaboration opportunity has been formally approved.',
    type: 'success',
    isRead: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    link: '/opportunities',
  },
  {
    id: 'notif-3',
    title: 'Upcoming Event Reminder',
    message: 'Annual Partnership Summit starts tomorrow at 9:00 AM.',
    type: 'warning',
    isRead: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    link: '/events',
  },
  {
    id: 'notif-4',
    title: 'System Maintenance',
    message: 'Scheduled maintenance will occur this Saturday at 2:00 AM EAT.',
    type: 'error',
    isRead: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'notif-5',
    title: 'New User Registered',
    message: 'Alexander M. has joined the platform.',
    type: 'info',
    isRead: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    link: '/users',
  },
]
